import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>calvin.art</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='no-mrg'>
        <div className='home-page down-flex gap'>
          <div className='simple-flex f-start2 gap wrap'>
            <Image height="100" width="100" src="https://media.licdn.com/dms/image/C4E03AQGIYK3XldkWTg/profile-displayphoto-shrink_800_800/0/1610592340250?e=2147483647&v=beta&t=MTpZSvvvg4ae3vJnelBgNFq1sFZessIJq7e_zndbn-g"/>
            <div className='down-flex'>
              <h1 className='no-mrg'>calvin.art</h1>
              <p>Hi, I'm Calvin. I'm a web developer and artist currently exploring the leverage of intelligent systems.</p>
            </div>
          </div>
          <div className='simple-flex f-start2 gap wrap'>
            <Link href="https://twitter.com/calvinducharme">
              <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24">
                <path fill="white" d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/>
              </svg>
            </Link>
            <Link href="mailto:calvinducharme@gmail.com">
            <svg height="32" viewBox="0 0 251 189" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M7 7L123 105L244 7M7 7V182H244V7M7 7H244" stroke="white" stroke-width="14" stroke-linejoin="round"/>
            </svg>
            </Link>
            <Link href="https://github.com/calvinusesyourcode">
              <svg height="32" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="32" data-view-component="true" class="octicon octicon-mark-github v-align-middle">
                <path d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z" fill="white"></path>
              </svg>
            </Link>
            <i>html, css, javascript, python </i>
            </div>
            <h2>projects</h2>
            <div>
              <Link href="https://www.pedenindustries.ca/">
              <svg id="logo-svg" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="50 50 807.34 96" className='yellow'><path d="M72,38c233,.33,275-.33,508,0a8.42,8.42,0,0,1,7-6,8.26,8.26,0,0,1,6,2l98-13,2,1,32-4,7-8h14l11,8,8,3,35,25,1,3,20,14a4.44,4.44,0,0,1,4,0c1.68,1.06,2.32,3.72,1,6l4,13a5,5,0,0,1,4,3,5.12,5.12,0,0,1-2,6c.7.72,8,8.42,6,19a21.86,21.86,0,0,1-17,17l-37,1v-3a39,39,0,0,0,11-5c13.37-8.85,17-23.49,18-28L755,53c-291.33.33-391.67,1.67-683,2A26.6,26.6,0,0,0,49,76v42a23.23,23.23,0,0,0,7,16,22.74,22.74,0,0,0,13,6c316.33,0,441.67-1,758-1l-12,18c-313,0-435,1-748,1a41.29,41.29,0,0,1-36-40V76A41.11,41.11,0,0,1,72,38Zm666-1-5-7V27l-6-6-34,4-1,1L615,38Zm77,32,2-4L765,27l39,43,5-4Zm7,11c1.31-1.06,1.26-4,0-7l-9,3C816.22,80.23,820.41,81.28,822,80Z" transform="translate(30 40) scale(.61 .6)" fill="white"/><text className="logo-text" transform="translate(70 114) scale(.5 .5)">PEDEN INDUSTRIES</text></svg>
              </Link>
              <div className='pad-sides'>
                <p>scope: web dev, advertising</p>
                <p>tech stack: next, react, firebase</p>
                <p>challenges: live database fetch/post, email notification system, image to webp cloud function, landing page optimization, advertising diversification</p>
              </div>
            </div>
          </div>
      </main>
    </>
  )
}
